services:
  - type: web
    name: climb-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import os; print('Build env DATABASE_URL:', os.environ.get('DATABASE_URL'))"
    startCommand: |
      python -c "import os; print('Start env DATABASE_URL:', os.environ.get('DATABASE_URL'))"
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: climb-db
          property: connectionString
      - key: POSTGRES_DB
        fromDatabase:
          name: climb-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: climb-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: climb-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: climb-db
          property: host
    healthCheckPath: /
    autoDeploy: true
    branch: master

databases:
  - name: climb-db
    databaseName: climbdb
    user: climb_user
    ipAllowList: [] # only allow internal connections
    plan: free
    region: oregon
