services:
  - type: web
    name: climb-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: climb-db
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: climb-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true
    branch: master

databases:
  - name: climb-db
    databaseName: climbdb
    user: climb_user
    plan: free
    region: oregon
    postDeploy: |
      psql $DATABASE_URL -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
