services:
  - type: web
    name: climb-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app --timeout 25 --workers 1 --worker-class sync
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          type: postgres
          name: climb-db
          property: internalDatabaseUrl
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          type: postgres
          name: climb-db
          property: internalDatabaseUrl
      # Memory and performance settings optimized for free tier
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PYTHON_MEMORY_LIMIT
        value: "400"
      - key: SQLALCHEMY_POOL_SIZE
        value: "2"
      - key: SQLALCHEMY_MAX_OVERFLOW
        value: "1"
      - key: GUNICORN_TIMEOUT
        value: "25"
      - key: GUNICORN_WORKERS
        value: "1"
      - key: GUNICORN_THREADS
        value: "1"
    disk:
      name: logs
      mountPath: /opt/render/project/src/logs
      sizeGB: 1

databases:
  - name: climb-db
    databaseName: climbdb
    user: climb_user
    plan: free
    region: oregon
    postgresMajorVersion: "16"
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
